### ISSUE TITLE
Queue Clear_Feature Request 

### ISSUE THREAD

**Issue by sm8928** [RobotExMachina/Machina-Bridge#1]
Can we have the ability to clear the 'Queue'.
Thanks.

**Comment by garciadelcastillo** [comment]
This should link to some low-level API in the core library.

**Comment by garciadelcastillo** [comment]
Added a lot of queue goodness to this release:

https://github.com/RobotExMachina/Machina-Bridge/releases/tag/v0.8.12

How does this look @sm8928 ? :)

**Comment by nonoesp** [comment]
Woot, woot! Happy to see things are moving. 🙂🦾🤖

**Comment by garciadelcastillo** [comment]
:)
