### ISSUE TITLE
help: UR 10e robot Ethernet connection 

### ISSUE THREAD

**Issue by garciadelcastillo** [RobotExMachina/Machina-Bridge#2]
Copy-pasted an email thread about problems setting up the ethernet connection with UR robots. 

---
Hi Kim, 

That is very strange, usually the capacity to ping the robot is good enough to make things work. 

Two ideas: 

-	Can this be a firewall/security problem? Does the bridge have all permissions to do network communication? Maybe the system is blocking its capacity to communicate over the network with some firewall or something. Make sure you run the Bridge in admin mode, and is fully whitelisted on your Windows Defender, Firewall settings, etc.
-	Maybe communication is blocked at the router level? Have you tried using a different router? I don’t think you can connect directly with an ethernet cable to the controller...

For the sake of better info, please set console level to “5 – DEBUG” on the top right corner, and try to connect. This should give you an extended error message and detailed info of why it cannot connect. Please post the screenshot here. 

---
Hi JL,

Thank you for your reply! We're glad to hear you find our work interesting.

We've tried both a direct setup connecting a cat 6e ethernet cable directly from a laptop to the ethernet port in the control box, as well as using a router. In both cases, we were able to ping the robot using the command prompt. We have also been trying to use RoboDK studio and have managed to ping the robot through their interface but have not been able to establish a connection either. 

We very much appreciate your help.

Best,

Kim 

 
---
Hi Kim, 
 
Were you able to figure this out? It is very strange that you can ping the robot but not connect to it. Can you describe to me your network setup? Are you connecting to the robot through a router? Or directly to the controller? 
 
Thanks, best
 
 
JL
 
 
 
---
Dear Garcia del Castillo,
 
We have recently bought a UR 10e robotic arm and are trying to connect it to our laptops through a modem using an ethernet connection. We have found your youtube videos very helpful but for some reason, we are still not able to connect to the robot even after successfully "pinging" the robot with a command prompt. The laptop we are using has a IP address of 192.168.1.46 which is why we gave the robot an IP address of 192.168.1.45 which allowed us to ping the robot and have it respond to the laptop. however, when we open up machina bridge we have not been able to connect to the robot. 
 
We would very much appreciate your help.
 
Best,
 
Kim

**Comment by gegardne** [comment]
Hi JL,
Thanks for your reply. 
We've tried using a different router, white listing machina in firewall and defender and running in admin mode. 
here is the error message we are getting from the console. 
![Capture](https://user-images.githubusercontent.com/49694986/56238645-2ff6df80-604c-11e9-83cd-858e35d592f7.JPG)
Let me know if you have any further suggestions. 
Best,
Guy

**Comment by wsvdyk** [comment]
hi @gegardne,

I have no UR robot and haven't tested machinabridge on a real robot yet, but is it possible that your router is blocking port 7000(default port in machinaBridge)? If you are not sure, go into the settings of your router and lookup "port forwarding".

This can explain why you can ping but not connect with your robot.

best,

Wesley

**Comment by garciadelcastillo** [comment]
Hi @gegardne,

I am sorry, but I am not sure then what the problem might be... Perhaps you could run some socket testing tools to figure out if there are problems in the way the applications are communicating... But physical debugging is hard from a distance :(

Please let us know if you find what the problem was. Good luck! 


JL

**Comment by garciadelcastillo** [comment]
Any luck with this @gegardne ?

**Comment by garciadelcastillo** [comment]
Closing do to inactivity
