### ISSUE TITLE
machina-bridge connection problem

### ISSUE THREAD

**Issue by Hazalyilmaz** [RobotExMachina/Machina-Bridge#5]
Hi!
We are working with ur5 for a real-time project. We followed your tutorial, but when we tried to connect the physical robot from Machina-bridge, it gives an error.  On the teach pendant it is written that "network is connected", and from the command prompt, we can successfully ping the connection. However, from machina-bridge we are not able to connect physical robot. 
I have posted the screenshots ( 1 from teach pendant second one from machina-bridge).
 Thanks in advance!!

![ur-error](https://user-images.githubusercontent.com/46568111/66272694-57956a80-e86d-11e9-9d36-b5fb7dbfd6e2.jpeg)

![ur-error2](https://user-images.githubusercontent.com/46568111/66272702-611ed280-e86d-11e9-90a0-16c69356f218.jpeg)

**Comment by garciadelcastillo** [comment]
Hi @Hazalyilmaz,

Not sure what the problem might be; setting up network communication is always quite dependent on the configuration of local machines, hardware, etc.

Things to keep in mind/try:

- Are you connecting via a router? For URs this is a better way than plugging your laptop directly into the ethernet port. 

- Can you ping the robot from a terminal? 

- If working on Windows, make sure that you don't use Windows Explorer to unzip the Bridge files, i.e. use a third party tool like 7z, winrar, etc. 

- If working on Windows, try running the Bridge with and without admin privileges. 

- Make sure the Bridge is not being capped by the Firewall. 

- Can you use the bridge to communicate with RobotStudio? Can you successfully control a virtual robot in RS from the Bridge?

If the answer to all the above is Yes, then I am not sure what's going on. 

I see your URSim is more modern than I have tested, which version is it? Something may have broken on the upgrade? 

Please keep us posted with progress.

**Comment by garciadelcastillo** [comment]
@Hazalyilmaz can you try something else? Can you try manually uploading and running the UR driver module that Machina uses to communicate with the robot? You can find it here: 

https://github.com/RobotExMachina/Machina.NET/blob/master/src/Machina/Resources/DriverModules/UR/machina_ur_driver.script

If this doesn't work, then we know where to start searching for the culprit. 

Thanks,

**Comment by Hazalyilmaz** [comment]
hey sorry for the late reply.  The problem for me was also "router"! without the router, it kept giving the connection error. but with router it solved.

**Comment by garciadelcastillo** [comment]
Wonderful, thank you both!
